#!/usr/bin/env python3
"""
Script para corrigir as referências de imagens no Módulo 4 e restaurar a formatação
"""

import json

def fix_module4_formatting_and_images():
    """Corrige a formatação e referências de imagens no Módulo 4"""
    
    # Ler o notebook atual
    with open('curso/04_transfer_learning_aplicacoes_praticas.ipynb', 'r', encoding='utf-8') as f:
        notebook = json.load(f)
    
    # Reorganizar o conteúdo em células adequadas
    new_cells = []
    
    # Célula 1: Título e objetivos
    title_cell = {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Módulo 4: Transfer Learning e Aplicações Práticas\n",
            "\n",
            "## 🎯 Objetivos de Aprendizagem\n",
            "\n",
            "Ao final deste módulo, você será capaz de:\n",
            "\n",
            "- ✅ Compreender o conceito de transfer learning\n",
            "- ✅ Aplicar modelos pré-treinados em problemas específicos\n",
            "- ✅ Entender quando usar fine-tuning vs. feature extraction\n",
            "- ✅ Implementar transfer learning com PyTorch\n",
            "- ✅ Conhecer aplicações práticas no mercado\n",
            "\n",
            "---\n",
            "\n",
            "## 🔄 4.1 Transfer Learning em Visão Computacional\n",
            "\n",
            "### Conceito Fundamental\n",
            "\n",
            "**Transfer Learning** é uma técnica de machine learning que permite utilizar conhecimento adquirido em uma tarefa para melhorar o desempenho em uma tarefa relacionada. Em visão computacional, isso significa aproveitar modelos treinados em datasets massivos como ImageNet.\n",
            "\n",
            "![Transfer Learning - Conceito](https://cdn.jsdelivr.net/gh/rfapo/visao-computacional@main/images/modulo04/transfer_learning_conceito.png)\n",
            "\n",
            "### Definição e Características\n",
            "\n",
            "**Definição:**\n",
            "- **Utilização de conhecimento**: Aproveitar representações aprendidas em tarefas similares\n",
            "- **Modelos pré-treinados**: Redes treinadas em ImageNet com milhões de imagens\n",
            "- **Adaptação**: Ajustar o modelo para nova tarefa específica\n",
            "- **Eficiência**: Reduzir tempo e dados necessários para treinamento\n",
            "\n",
            "### Por que Funciona?\n",
            "\n",
            "![Por que Transfer Learning Funciona](https://cdn.jsdelivr.net/gh/rfapo/visao-computacional@main/images/modulo04/por_que_transfer_learning_funciona.png)\n",
            "\n",
            "#### **1. Features Universais**\n",
            "- **Primeiras camadas**: Aprendem características básicas (bordas, texturas)\n",
            "- **Transferibilidade**: Características baixo-nível são universais\n",
            "- **Reutilização**: Aplicáveis a diferentes domínios\n",
            "\n",
            "#### **2. Hierarquia de Abstração**\n",
            "- **Camadas profundas**: Capturam conceitos específicos\n",
            "- **Progressão**: Simples → Complexo → Específico\n",
            "- **Adaptação**: Ajuste fino para nova tarefa\n",
            "\n",
            "#### **3. Economia de Recursos**\n",
            "- **Tempo**: Até 10x mais rápido que treino do zero\n",
            "- **Dados**: Requer 5-10x menos dados de treinamento\n",
            "- **Computação**: Menos recursos necessários\n",
            "\n",
            "### Benefícios Quantitativos\n",
            "\n",
            "| Métrica | Transfer Learning | Treino do Zero | Melhoria |\n",
            "|---------|-------------------|----------------|----------|\n",
            "| **Tempo de Treinamento** | 2-4 horas | 20-40 horas | 10x |\n",
            "| **Dados Necessários** | 1K-5K imagens | 10K-50K imagens | 10x |\n",
            "| **Acurácia Inicial** | 80-90% | 60-70% | +20% |\n",
            "| **Convergência** | 10-20 épocas | 50-100 épocas | 5x |\n",
            "\n",
            "---\n",
            "\n",
            "## 🎯 4.2 Estratégias de Transfer Learning\n",
            "\n",
            "### Comparação das Abordagens\n",
            "\n",
            "![Comparação das Estratégias de Transfer Learning](https://cdn.jsdelivr.net/gh/rfapo/visao-computacional@main/images/modulo04/estrategias_comparacao.png)\n",
            "\n",
            "#### **1. Feature Extraction**\n",
            "\n",
            "![Feature Extraction](https://cdn.jsdelivr.net/gh/rfapo/visao-computacional@main/images/modulo04/feature_extraction.png)\n",
            "\n",
            "**Características:**\n",
            "- **Congelamento**: Todas as camadas congeladas\n",
            "- **Treinamento**: Apenas camada de classificação\n",
            "- **Velocidade**: Muito rápido\n",
            "- **Dados**: Poucos dados necessários\n",
            "\n",
            "**Quando Usar:**\n",
            "- Dataset muito pequeno (< 1K imagens)\n",
            "- Domínio similar ao ImageNet\n",
            "- Recursos computacionais limitados\n",
            "- Prototipagem rápida\n",
            "\n",
            "**Vantagens:**\n",
            "- ✅ Treinamento muito rápido\n",
            "- ✅ Poucos dados necessários\n",
            "- ✅ Estável e confiável\n",
            "- ✅ Fácil de implementar\n",
            "\n",
            "**Desvantagens:**\n",
            "- ❌ Performance limitada\n",
            "- ❌ Não se adapta ao domínio\n",
            "- ❌ Pode não funcionar bem em domínios muito diferentes\n",
            "\n",
            "#### **2. Fine-tuning**\n",
            "\n",
            "![Fine-tuning](https://cdn.jsdelivr.net/gh/rfapo/visao-computacional@main/images/modulo04/fine_tuning.png)\n",
            "\n",
            "**Características:**\n",
            "- **Descongelamento**: Camadas finais descongeladas\n",
            "- **Treinamento**: Camadas finais + classificação\n",
            "- **Velocidade**: Moderado\n",
            "- **Dados**: Quantidade moderada necessária\n",
            "\n",
            "**Quando Usar:**\n",
            "- Dataset médio (1K-10K imagens)\n",
            "- Domínio similar ao ImageNet\n",
            "- Recursos computacionais moderados\n",
            "- Balance entre velocidade e performance\n",
            "\n",
            "**Vantagens:**\n",
            "- ✅ Boa performance\n",
            "- ✅ Adaptação ao domínio\n",
            "- ✅ Treinamento moderado\n",
            "- ✅ Flexibilidade\n",
            "\n",
            "**Desvantagens:**\n",
            "- ❌ Mais dados necessários\n",
            "- ❌ Risco de overfitting\n",
            "- ❌ Mais complexo de implementar\n",
            "\n",
            "#### **3. Pre-trained Initialization**\n",
            "\n",
            "![Pre-trained Initialization](https://cdn.jsdelivr.net/gh/rfapo/visao-computacional@main/images/modulo04/pre_trained_initialization.png)\n",
            "\n",
            "**Características:**\n",
            "- **Inicialização**: Pesos pré-treinados como ponto de partida\n",
            "- **Treinamento**: Todas as camadas treinadas\n",
            "- **Velocidade**: Lento\n",
            "- **Dados**: Muitos dados necessários\n",
            "\n",
            "**Quando Usar:**\n",
            "- Dataset grande (> 10K imagens)\n",
            "- Domínio diferente do ImageNet\n",
            "- Recursos computacionais abundantes\n",
            "- Performance máxima necessária\n",
            "\n",
            "**Vantagens:**\n",
            "- ✅ Melhor performance\n",
            "- ✅ Adaptação completa ao domínio\n",
            "- ✅ Flexibilidade máxima\n",
            "- ✅ Aproveitamento de conhecimento\n",
            "\n",
            "**Desvantagens:**\n",
            "- ❌ Treinamento lento\n",
            "- ❌ Muitos dados necessários\n",
            "- ❌ Risco de overfitting\n",
            "- ❌ Complexo de implementar\n",
            "\n",
            "### Comparação Quantitativa\n",
            "\n",
            "| Estratégia | Dados | Tempo | Performance | Complexidade |\n",
            "|------------|-------|-------|-------------|--------------|\n",
            "| **Feature Extraction** | Poucos | Muito Rápido | Boa | Baixa |\n",
            "| **Fine-tuning** | Moderados | Rápido | Muito Boa | Média |\n",
            "| **Pre-trained Init** | Muitos | Lento | Excelente | Alta |\n",
            "\n",
            "---\n",
            "\n",
            "## 🏭 4.4 Aplicações Práticas no Mercado\n",
            "\n",
            "### Casos de Uso Reais\n",
            "\n",
            "![Aplicações Práticas](https://cdn.jsdelivr.net/gh/rfapo/visao-computacional@main/images/modulo04/aplicacoes_praticas.png)\n",
            "\n",
            "#### **1. Medicina e Saúde**\n",
            "\n",
            "**Aplicações:**\n",
            "- Diagnóstico por imagem: Raios-X, ressonância magnética\n",
            "- Detecção de câncer: Mamografia, dermatologia\n",
            "- Análise de patologias: Histologia, citologia\n",
            "\n",
            "**Exemplo Prático:**\n",
            "- Dataset: 1000 imagens de raios-X de pulmão\n",
            "- Estratégia: Fine-tuning com ResNet-50\n",
            "- Resultado: 95% de acurácia em detecção de pneumonia\n",
            "- Tempo: 2 horas vs 20 horas (treino do zero)\n",
            "\n",
            "#### **2. Agricultura e Meio Ambiente**\n",
            "\n",
            "**Aplicações:**\n",
            "- Monitoramento de culturas: Detecção de doenças\n",
            "- Análise de solo: Classificação de tipos\n",
            "- Detecção de pragas: Identificação de insetos\n",
            "\n",
            "**Exemplo Prático:**\n",
            "- Dataset: 5000 imagens de folhas de plantas\n",
            "- Estratégia: Feature extraction com VGG-16\n",
            "- Resultado: 90% de acurácia em classificação de doenças\n",
            "- Tempo: 30 minutos vs 5 horas\n",
            "\n",
            "#### **3. Indústria e Manufatura**\n",
            "\n",
            "**Aplicações:**\n",
            "- Controle de qualidade: Detecção de defeitos\n",
            "- Classificação de produtos: Categorização automática\n",
            "- Inspeção de equipamentos: Manutenção preventiva\n",
            "\n",
            "**Exemplo Prático:**\n",
            "- Dataset: 2000 imagens de peças industriais\n",
            "- Estratégia: Fine-tuning com AlexNet\n",
            "- Resultado: 98% de acurácia em detecção de defeitos\n",
            "- Tempo: 1 hora vs 10 horas\n",
            "\n",
            "#### **4. Varejo e E-commerce**\n",
            "\n",
            "**Aplicações:**\n",
            "- Reconhecimento de produtos: Busca por imagem\n",
            "- Classificação de categorias: Organização automática\n",
            "- Análise de sentimentos: Avaliação de produtos\n",
            "\n",
            "**Exemplo Prático:**\n",
            "- Dataset: 10000 imagens de produtos\n",
            "- Estratégia: Pre-trained initialization com ResNet-101\n",
            "- Resultado: 96% de acurácia em classificação\n",
            "- Tempo: 4 horas vs 40 horas\n",
            "\n",
            "### Comparação de Domínios\n",
            "\n",
            "| Domínio | Dataset Típico | Estratégia Recomendada | Acurácia | Tempo |\n",
            "|---------|----------------|------------------------|----------|-------|\n",
            "| **Medicina** | 1K-5K | Fine-tuning | 90-95% | 2-4h |\n",
            "| **Agricultura** | 500-2K | Feature extraction | 85-90% | 30min-1h |\n",
            "| **Indústria** | 1K-3K | Fine-tuning | 95-98% | 1-2h |\n",
            "| **Varejo** | 5K-20K | Pre-trained init | 95-98% | 4-8h |\n",
            "\n",
            "---\n",
            "\n",
            "## 📝 Resumo do Módulo 4\n",
            "\n",
            "### Principais Conceitos Abordados\n",
            "\n",
            "1. **Fundamentos**: Transfer learning e reutilização de conhecimento\n",
            "2. **Estratégias**: Feature extraction, fine-tuning, pre-trained initialization\n",
            "3. **Aplicações**: Casos reais em diferentes domínios\n",
            "4. **Implementação**: Pipeline completo com PyTorch\n",
            "5. **Comparação**: Análise quantitativa de estratégias\n",
            "\n",
            "### Próximos Passos\n",
            "\n",
            "No **Módulo 5**, aplicaremos essas técnicas em tarefas fundamentais de visão computacional: classificação, detecção e segmentação.\n",
            "\n",
            "### Referências Principais\n",
            "\n",
            "- [How transferable are features in deep neural networks? - Yosinski et al.](https://papers.nips.cc/paper/2014/hash/375c71349b295fbe2dcdca9206f20a06-Abstract.html)\n",
            "- [Transfer Learning for Computer Vision - Pan & Yang](https://ieeexplore.ieee.org/document/5288526)\n",
            "\n",
            "---\n",
            "\n",
            "**Próximo Módulo**: Tarefas Fundamentais de Visão Computacional"
        ]
    }
    
    new_cells.append(title_cell)
    
    # Salvar o notebook corrigido
    with open('curso/04_transfer_learning_aplicacoes_praticas.ipynb', 'w', encoding='utf-8') as f:
        json.dump({'cells': new_cells, 'metadata': {'language_info': {'name': 'python'}}, 'nbformat': 4, 'nbformat_minor': 2}, f, ensure_ascii=False, indent=1)
    
    print("✅ Módulo 4 corrigido com sucesso!")
    print("📸 Referências de imagens atualizadas para modulo04/")
    print("🔧 Formatação restaurada")

if __name__ == "__main__":
    fix_module4_formatting_and_images()
